feat: introduce eXo parent pom - EXO-64103
exoplatform/commons-exo pull request #2
Opened 2023-05-04 12:54 UTC by rdenarie

This feature introduce new parent pom for eXo to be able to declare libraries versions used only in eXo, without impacting meeds

2023-05-04 14:07 UTC, azayati requested changes

2023-05-04 14:07 UTC, azayati commented on pom.xml
> +  <name>eXo PLF:: Commons eXo Platform</name>
```suggestion
  <name>eXo PLF:: eXo Platform Commons</name>
```

2023-05-04 14:57 UTC, azayati approved these changes
LGTM

2023-05-05 10:32 UTC, ahamdi approved these changes

2023-05-16 07:44 UTC, merged